V33 fix dss script
moka-guys/automate_demultiplex pull request #294
Opened 2020-11-03 17:05 UTC by aledj2

2020-11-03 17:24 UTC, natashapinto commented on automate_demultiplex_config.py
> +runfolders = "/media/data3/share/testing"
Is it meant to point to a test folder?

2020-11-04 09:13 UTC, natashapinto requested changes
Just a comment on where the runfolder path is pointing to

2020-11-04 11:35 UTC, aledj2 reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/294)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[automate_demultiplex_config.py, line 22 at r1](https://reviewable.io/reviews/moka-guys/automate_demultiplex/294#-MLE3ba77jkDWpCybwSW-r1-22:-MLI1Z-J6q00xxFjo8QD:b-896fix) ([raw file](https://github.com/moka-guys/automate_demultiplex/blob/10cbec787eab49ffce94f4f9eac6f9358a053764/automate_demultiplex_config.py#L22)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

Is it meant to point to a test folder?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-04 11:37 UTC, natashapinto approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/automate_demultiplex/294)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-04 11:38 UTC, merged